DROP TABLE frases;
DROP TABLE puntuaciones;
CREATE TABLE IF NOT EXISTS frases (
id_frase INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
contenido VARCHAR(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS puntuaciones (
id_partida INT AUTO_INCREMENT PRIMARY KEY,
nombre_usuario VARCHAR(20),
puntuacion_final INT
);
INSERT INTO puntuaciones (
nombre_usuario,
puntuacion_final
)
VALUES
    ("Superman", 100),("Inframan", 101),("Polnareff", 135),("Drinking bird", 149),("Soy admin",500);
INSERT INTO frases (contenido)
VALUES
    ("I was starting to worry that my pet turtle could tell what I was thinking."),
    ("Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn''t and they don''t recommend anyone else do it either."),
    ("She had some amazing news to share but nobody to share it with."),
    ("She always had an interesting perspective on why the world must be flat."),
    ("As he looked out the window, he saw a clown walk by."),
    ("I''m confused: when people ask me what''s up, and I point, they groan."),
    ("The door swung open to reveal pink giraffes and red elephants."),
    ("The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle''s disappearance."),
    ("Kelly wouldn''t have eaten the meal if she had known what it actually was."),
    ("The urgent care center was flooded with patients after the news of a new deadly virus was made public."),
    ("The bullet pierced the window shattering it before missing Danny''s head by mere millimeters."),
    ("His ultimate dream fantasy consisted of being content and sleeping eight hours in a row."),
    ("She is never happy until she finds something to be unhappy about; then, she is overjoyed."),
    ("When she didn''t like a guy who was trying to pick her up, she started using sign language."),
    ("Her life in the confines of the house became her new normal."),
    ("Three generations with six decades of life experience."),
    ("As the rental car rolled to a stop on the dark road, her fear increased by the moment."),
    ("She wanted a pet platypus but ended up getting a duck and a ferret instead."),
    ("I am counting my calories, yet I really want dessert."),
    ("The light in his life was actually a fire burning all around him."),
    ("Karen realized the only way she was getting into heaven was to cheat."),
    ("Honestly, I didn''t care much for the first season, so I didn''t bother with the second."),
    ("She saw the brake lights, but not in time."),
    ("The ice-cream trucks bring back bad memories for all of us."),
    ("You can''t compare apples and oranges, but what about bananas and plantains?"),
    ("He invested some skill points in Charisma and Strength."),
    ("The teenage boy was accused of breaking his arm simply to get out of the test."),
    ("He''s in a boy band which doesn''t make much sense for a snake."),
    ("You''re unsure whether or not to trust him, but very thankful that you wore a turtle neck."),
    ("The changing of down comforters to cotton bedspreads always meant the squirrels had returned."),
    ("I may struggle with geography, but I''m sure I''m somewhere around here."),
    ("The glacier came alive as the climbers hiked closer."),
    ("He poured rocks in the dungeon of his mind."),
    ("This is a Japanese doll."),
    ("He figured a few sticks of dynamite were easier than a fishing pole to catch fish."),
    ("He embraced his new life as an eggplant."),
    ("There''s no reason a hula hoop can''t also be a circus ring."),
    ("The bread dough reminded her of Santa Clause''s belly."),
    ("It''s difficult to understand the lengths he''d go to remain short."),
    ("Everyone says they love nature until they realize how dangerous she can be."),
    ("One small action would change her life, but whether it would be for better or for worse was yet to be determined."),
    ("Most shark attacks occur about 10 feet from the beach since that''s where the people are."),
    ("The best part of marriage is animal crackers with peanut butter."),
    ("Toddlers feeding raccoons surprised even the seasoned park ranger."),
    ("They were excited to see their first sloth."),
    ("The waitress was not amused when he ordered green eggs and ham."),
    ("She found it strange that people use their cellphones to actually talk to one another."),
    ("He didn''t want to go to the dentist, yet he went anyway."),
    ("The blue parrot drove by the hitchhiking mongoose."),
    ("The spa attendant applied the deep cleaning mask to the gentleman''s back."),
    ("Lucifer was surprised at the amount of life at Death Valley."),
    ("The near-death experience brought new ideas to light."),
    ("It would have been a better night if the guys next to us weren''t in the splash zone."),
    ("Being unacquainted with the chief raccoon was harming his prospects for promotion."),
    ("There are over 500 starfish in the bathroom drawer."),
    ("Beach-combing replaced wine tasting as his new obsession."),
    ("Shingle color was not something the couple had ever talked about."),
    ("You have no right to call yourself creative until you look at a trowel and think that it would make a great lockpick."),
    ("The mysterious diary records the voice."),
    ("It''s always a good idea to seek shelter from the evil gaze of the sun."),
    ("She discovered van life is difficult with 2 cats and a dog."),
    ("The quick brown fox jumps over the lazy dog."),
    ("His mind was blown that there was nothing in space except space itself."),
    ("He spiked his hair green to support his iguana."),
    ("She could hear him in the shower singing with a joy she hoped he''d retain after she delivered the news."),
    ("He found a leprechaun in his walnut shell."),
    ("He appeared to be confusingly perplexed."),
    ("I''m not a party animal, but I do like animal parties."),
    ("With a single flip of the coin, his life changed forever."),
    ("Rock music approaches at high velocity."),
    ("There''s a growing trend among teenagers of using frisbees as go-cart wheels."),
    ("Let me help you with your baggage."),
    ("Some bathing suits just shouldn''t be worn by some people."),
    ("Pantyhose and heels are an interesting choice of attire for the beach."),
    ("He always wore his sunglasses at night."),
    ("There have been days when I wished to be separated from my body, but today wasn''t one of those days."),
    ("His get rich quick scheme was to grow a cactus farm."),
    ("You''ve been eyeing me all day and waiting for your move like a lion stalking a gazelle in a savannah."),
    ("Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon."),
    ("The Great Dane looked more like a horse than a dog."),
    ("He colored deep space a soft yellow."),
    ("My dentist tells me that chewing bricks is very bad for your teeth."),
    ("Edith could decide if she should paint her teeth or brush her nails."),
    ("He watched the dancing piglets with panda bear tummies in the swimming pool."),
    ("So long and thanks for the fish."),
    ("Patrick ordered a ghost pepper pie."),
    ("Watching the geriatric men''s softball team brought back memories of 3 year olds playing football."),
    ("They ran around the corner to find that they had traveled back in time."),
    ("A song can make or ruin a person''s day if they let it get to them."),
    ("She lived on Monkey Jungle Road and that seemed to explain all of her strangeness."),
    ("Tuesdays are free if you bring a gnome costume."),
    ("It had been sixteen days since the zombies first attacked."),
    ("Truth in advertising and dinosaurs with skateboards have much in common."),
    ("On a scale from one to ten, what''s your favorite flavor of random grammar?"),
    ("Art doesn''t have to be intentional."),
    ("Kevin embraced his ability to be at the wrong place at the wrong time."),
    ("You bite up because of your lower jaw."),
    ("I can''t believe this is the eighth time I''m smashing open my piggy bank on the same day!"),
    ("The beach was crowded with snow leopards."),
    ("In that instant, everything changed."),
    ("Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn''t so bad after all."),
    ("Grape jelly was leaking out the hole in the roof."),
    ("Not all people who wander are lost."),
    ("The sunblock was handed to the girl before practice, but the burned skin was proof she did not apply it."),
    ("The child''s favorite Christmas gift was the large box her father''s lawnmower came in."),
    ("She found his complete dullness interesting."),
    ("She had some amazing news to share but nobody to share it with."),
    ("He went on a whiskey diet and immediately lost three days."),
    ("He shaved the peach to prove a point."),
    ("After coating myself in vegetable oil I found my success rate skyrocketed."),
    ("Everyone was busy, so I went to the movie alone."),
    ("I caught my squirrel rustling through my gym bag."),
    ("I''m confused: when people ask me what''s up, and I point, they groan."),
    ("He wasn''t bitter that she had moved on but from the radish."),
    ("The underground bunker was filled with chips and candy."),
    ("They''re playing the piano while flying in the plane."),
    ("He told us a very exciting adventure story."),
    ("In hopes of finding out the truth, he entered the one-room library."),
    ("Harrold felt confident that nobody would ever suspect his spy pigeon."),
    ("The wake behind the boat told of the past while the open sea for told life in the unknown future.");